name: ai_barcode_scanner
description: A universal AI barcode and QR code scanner for Flutter based on MLKit. Uses CameraX on Android, AVFoundation on iOS and Apple Vision & AVFoundation on macOS.
version: 7.0.0
homepage: https://mohesu.com
repository: https://github.com/itsarvinddev/barcode_scanner.git
issue_tracker: https://github.com/itsarvinddev/barcode_scanner/issues
screenshots:
  - description: "AI Barcode Scanner"
    path: assets/ai_barcode_scanner.png
  - description: "UI Customization"
    path: assets/IMG_5359.png

topics:
  - qr-code
  - barcode
  - scanner
  - camera
  - mobile-scanner

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: 6.0.11
  image_picker: ^1.1.2
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
